resolvers += Resolver.sonatypeRepo("snapshots")

addSbtPlugin("com.eed3si9n"              % "sbt-projectmatrix"         % "0.9.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.4.1")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"              % "2.5.0")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"            % "1.5.11")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"              % "0.10.4")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"                % "5.9.0")
addSbtPlugin("com.indoorvivants"         % "subatomic-plugin"          % "0.0.7+118-4f1e745e-SNAPSHOT")
addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates"    % "1.2.7")
