name: CI
on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3      
      
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      
      - name: Build site
        run: sbt "compile; docs/run build --destination $(pwd)/_site"

  release:
    name: Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/master')
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: coursier/cache-action@v3      
      
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      
      - run: git fetch --unshallow
      
      - name: Publish ${{ github.ref }}
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      
      - name: Build site
        run: sbt "compile; docs/run build --destination $(pwd)/_site"
      
      - name: Publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
