name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3      
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Build mdoc
        run: sbt docs/mdoc
      - name: Print out generated files
        run: cat ce-docs/target/mdoc/*.md

  

